language: node_js
node_js:
- 12.18.3
cache: npm
install:
- npm ci
script:
- npm test
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: UF022D/WfR8UwIQEyJuOtlX5k+uj60hrAW3qwgDHmEPm5PuZc9iazz77RhGaFEoxyd79fJ70Fr11oglGJWvkYwHmcJOYF+x7igkJarVzDOmLnhEI2k8rl2N1MZrVO7bOPRt4C6Q/fwMrnwI4c9Son5jJcXayH+t5ugetFrRg1FbpDLuy2e2GqgK5TVs02vT2+b/Ca8CR728+8VZqNGPIEXKipTVnnkXQdQUJo1RlIlIVs8nc1fDbyrccO9lv+5I7AvKKLG3EpZ8mbcXgiHTp0I43BqtD2hBYJ5BhoIefF35CnDVmH/EJ6HTIMavgsy2bSgcRuw1+B5YpqEIAwAixW5QLKqzLuNK8HetB7KEoqqNZJrClXgYQYaJHMNLnbn03Isj7Q3mKZ5AYSEfshSwUXQYnFMSvDk5D5d0m9TrVTrd9hSmBgiAmryuquQllmMdWsqI9x599QHcRMyLP+guSWz0+kjSucllhcUhRBdJAtgFOXauOp28JwnfG/WOzv5IZEW3SLLjUh1DFgV1sX2/507ZDHtMgS7dqhITMq4vP0TSxSyTVj53vqK3gZaKwCYDbsKH67P0oYSo903AITWndzJ5x7Hlm4w6kotyrKUTO8zAVVrcxzTmOy66Q++3p1JtfN6L03s0V+Uqnd0+uPWFTOlC6FffLhFUdEDJ4iH+In3Y=
