language: node_js
node_js:
- 12.18.3
cache: npm
install:
- npm ci
script:
- npm test
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: GHvQoJ5/Dq0tMF8eaUdfXaNb6RRgoUdO7hOrrUbCESt1VDVT0MgP8S5OsbhN2I7Rmad6ukGj8Phj8AQe1vNlpubwsDiYCb0SZOKFNPasVTL9XTDWpwtVVkokDBwGpQLOfT2KJKKJ3E6RyiFISIPKsNJOWh0LwZy+Fpbl6CCAYdT/mhiWkmqiHWF+bg97HrCilij6nPAJxG15SSaC/S8l6IxgLDV8ZW6yZL9U4dntPONuPwWhk48RDEvTy2WXmkMvubi+2i3GaW8BxSYwsydbxqnAcEEIFt8tpAVPit2MqT1IFfm0dwOXfWecFN3E1Q/Qm8kA6Xm0067U7a4ILTz7P9EQ6kEmHREbCZraliVmx+gfNPOHzkMW4vLvqXl4kOn6JOz0+aVMMO12o9DdLsIsDn7VUX5S9lG9ajT9DNtFjXl66pePXPTCBAvMl/HstAvr+mKw6BMoDu7557dqBdnZXJzghe5pm7ZdFkH0/Wu/3sI/XgVmbEhaXBq7WO8GbdHHh7bZleUXpr1k0R05UKGVeWyqD5FBzXTF+mBEPnrYzaeca7OezlyOWlOQIuJ4M8/CEvUeBLSguRRiY01VkeCPI9943FpM/lUB50UQDfQZYakZOGtRYnTJz6uAOOgNU+RNtcYQyAZIjS09kz2zW3JO7zwDDJLjpjMLsDkT4zyzR+8=
