language: node_js
node_js:
- 12.18.3
cache: npm
install:
- npm ci
script:
- npm test
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: R0t/YvCYXEO+96wTGBhmf+UJtdY0bh1ccmblrrMmztf6yLHmEZ15XV3Zu3r575ZzHJw+cAfpq+5zFRUDC5qrDY721pO5mxz4ZE+MDB46M4ak+QYsJi2tSGhJ/0fKFI0/yzxMUie2Gfuh7xmuUX6a8Eo5G/aNXV08ptKkONZHVFnO4A/6zop4YNpRJOLxv/kbgpySus63feMoW/UA3EVeD77IlSheDhek6csrnKCMQB9ZhC15MvoUFWv0F1JQLnHq4JammwkDYkTFk0T6U3W0ROtUvzmDP5j3MpEiAySz7sun7iRnUAeFQURqh/m8/13syVilx0DTgBpX0Kmw/fPqsLDZgOzrsH/V7slnlkgbM01lpVFwsr8wtcUl2OBXAF5y+B2RzzQl968RgPWyk1Svi4Esk0FvTks7uWSGmzT/yLujuXKxbK+piFexNu1t1LbDrKBVq8j4rU7SALtiiD8qQUX2PjrArTJT0mnzN1OuYxO5lcFvALKsKDIEoA5zbtSy4aVXwOUxW9VMkZqPmm+ShcdeD4gbZ34zfFKfGCIMXejyESwUdaIZRcCKv11v6Rf8Y4OhpevYqtwp80yL1SkDJgf/uTLXc0ujx5HK5NKNrij9vLzo306YUdTo+/Ppa7WWQjcld3WqGGig4cP4YlzylEvLL6jM+Qq//wSxwxfiul8=
