language: node_js
node_js:
- 12.18.3
cache: npm
install:
- npm ci
script:
- npm test
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: 
env:
  global:
    secure: brTIzwpQPsy2JfvDktRILCl2mPqAS5xPUOSPflpij27ScRP6UoZRYCEZLfV9zHZRjs/i6JBZqGAXhUt7KDlfmkoRF3mh9EbPcsYdHFBy1Z3VzgRNFTMV2ZrRLt8tOxx/260ZLGrJ0xecR/+46RVc0bFVnvduojyf725Ls+lN8Wblxbw0Oy1QITh2CloNZx/MWQgPx/GhYDlpv9WU7sG+OW5UXJ3g/rooDGzsUNuRVuHgBvjHArnunMZADDjXpFDZX3jJrRh4Ahz1ktkjHbj1DjJVzOT0OIU6KlDZhfspiGDXKvaHHBbitBRVAfAYZ0yrOv8SE04IfAGU6m9i7BAwi8cJgPfd45bznu7hy5S7a/Tfo/UBUPXnhVL+OYqyBrxT36W85US3+Wep7XGuMjWf6nsdlf7pKuSfxp4k8Dgl296uyJslNPKG/ts/YCGfiI/p/jl6I1kt/1wzRKt5i9dD+HyTungNY7Lw+2xQcwQH1SeKBaBi/KHqX2bMCZB/E91HUxEvNMkX52ZWN5FoUNRgihjAqZmeSvwWvAi6+cSNOVLZ1LET0TO+9h1ju2YnWj/Q0Ke68M/j8seyP0bOgCpacE+wuFJpGOuNfU/nZaNISJElRxNWszYOScB8SDw+o/JyAbf5QBajHlcE8o280eSAUwfQVUI+V4yxhfuF8DLgGN4=
